### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by TomClarkson** [dnbrwstr/colorchat-app#1]
This project looks great I would be keen to get the client and server up and running but I was wondering if you could you please provide install instructions, I tried to build the app but it failed saying Parse.plist could not be opened.

Could you please outline what I need to do to run the client and the server.

Many thanks

**Comment by dnbrwstr** [comment]
Thanks for taking a look -- I'll try to add basic docs and update the config files sometime this week. In the meantime, you should be able to get the client running by adding a Parse.plist file to the Xcode project, as shown below. 

![parse](https://cloud.githubusercontent.com/assets/357216/11354861/9cbe7ca0-921d-11e5-94d7-7b21d3626b6a.png)

**Comment by TomClarkson** [comment]
Thanks, this worked but I only got as far as the confirmation code screen. 

I guess I should wait for the docs - this code looks great, I'm sure I will learn heaps from it.

**Comment by dnbrwstr** [comment]
Have added some basic docs to this and the server repo, let me know if you're still running into issues!
